name: farmbridge_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  fl_chart: ^0.70.2
  flutter_launcher_icons: ^0.14.3
  flutter_map: ^8.1.1
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  firebase_storage: ^12.4.5
  location_picker_flutter_map: ^1.1.0
  flutter_location_search: ^2.0.0
  google_places_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    # path to image dir
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
